// Code generated by gofast. DO NOT EDIT.

package main

import (
	"fmt"
	"strings"
)

func (in LoginInput) Validate() error {
	if in.Email == "" {
		return fmt.Errorf("Email is required")
	}
	if !strings.Contains(in.Email, "@") {
		return fmt.Errorf("Email must be a valid email")
	}
	if in.Password == "" {
		return fmt.Errorf("Password is required")
	}
	if len(in.Password) < 8 {
		return fmt.Errorf("Password must be at least 8 characters")
	}
	return nil
}
