// Code generated by gofast. DO NOT EDIT.

package main

import (
	"net/url"
	"strconv"
)

func (i *ListTransactionsInput) BindQuery(values url.Values) {
	i.Page, _ = strconv.Atoi(values.Get("page"))
	if i.Page == 0 {
		i.Page = 1
	}
	i.Limit, _ = strconv.Atoi(values.Get("limit"))
	if i.Limit == 0 {
		i.Limit = 10
	}
}
