// internal/codegen/generate_bind.go
package codegen

import (
	"fmt"
	"strings"
)

func GenerateBindPath(packageName string, structs []StructInfo) string {
	var body strings.Builder

	body.WriteString("// Code generated by gofast. DO NOT EDIT.\n\n")
	body.WriteString("package " + packageName + "\n\n")

	wrote := false

	for _, s := range structs {
		fields := tagFields(s, "path")
		if len(fields) == 0 {
			continue
		}

		wrote = true
		fmt.Fprintf(&body, "func (i *%s) BindPath(params map[string]string) {\n", s.Name)
		for _, tf := range fields {
			fmt.Fprintf(&body, "\ti.%s = params[%q]\n", tf.FieldName, tf.ParamName)
		}
		body.WriteString("}\n\n")
	}

	if !wrote {
		return ""
	}

	return body.String()
}

func GenerateBindQuery(packageName string, structs []StructInfo) string {
	var body strings.Builder

	body.WriteString("// Code generated by gofast. DO NOT EDIT.\n\n")
	body.WriteString("package " + packageName + "\n\n")

	needsStrconv := false
	for _, s := range structs {
		for _, f := range tagFields(s, "query") {
			if f.FieldType == "int" {
				needsStrconv = true
			}
		}
	}

	if needsStrconv {
		body.WriteString("import (\n\t\"net/url\"\n\t\"strconv\"\n)\n\n")
	} else {
		body.WriteString("import \"net/url\"\n\n")
	}

	wrote := false

	for _, s := range structs {
		fields := tagFields(s, "query")
		if len(fields) == 0 {
			continue
		}

		wrote = true
		fmt.Fprintf(&body, "func (i *%s) BindQuery(values url.Values) {\n", s.Name)
		for _, qf := range fields {
			body.WriteString(generateQueryFieldAssign(qf))
		}
		body.WriteString("}\n\n")
	}

	if !wrote {
		return ""
	}

	return body.String()
}

type taggedField struct {
	FieldName    string
	FieldType    string
	ParamName    string
	DefaultValue string
}

func tagFields(s StructInfo, tagKey string) []taggedField {
	var result []taggedField
	for _, f := range s.Fields {
		rawValue := extractSimpleTag(f.Tag, tagKey)
		if rawValue == "" {
			continue
		}

		paramName, defaultValue := parseQueryTag(rawValue)

		result = append(result, taggedField{
			FieldName:    f.Name,
			FieldType:    f.Type,
			ParamName:    paramName,
			DefaultValue: defaultValue,
		})
	}
	return result
}

func generateQueryFieldAssign(qf taggedField) string {
	var out strings.Builder

	switch qf.FieldType {
	case "string":
		fmt.Fprintf(&out, "\ti.%s = values.Get(%q)\n", qf.FieldName, qf.ParamName)
		if qf.DefaultValue != "" {
			fmt.Fprintf(&out, "\tif i.%s == \"\" {\n\t\ti.%s = %q\n\t}\n", qf.FieldName, qf.FieldName, qf.DefaultValue)
		}
	case "int":
		fmt.Fprintf(&out, "\ti.%s, _ = strconv.Atoi(values.Get(%q))\n", qf.FieldName, qf.ParamName)
		if qf.DefaultValue != "" {
			fmt.Fprintf(&out, "\tif i.%s == 0 {\n\t\ti.%s = %s\n\t}\n", qf.FieldName, qf.FieldName, qf.DefaultValue)
		}
	default:
		fmt.Fprintf(&out, "\t// unsupported type %q for field %s, skipped\n", qf.FieldType, qf.FieldName)
	}

	return out.String()
}
