// internal/codegen/generate.go
package codegen

import (
	"fmt"
	"strings"
)

func GenerateValidate(packageName string, structs []StructInfo) string {
	var body strings.Builder

	body.WriteString("// Code generated by gofast. DO NOT EDIT.\n\n")
	body.WriteString("package " + packageName + "\n\n")
	body.WriteString("import (\n\t\"fmt\"\n\t\"strings\"\n)\n\n")

	validatableStructs := computeValidatableStructs(structs)

	wrote := false

	for _, s := range structs {
		rules := fieldRules(s)
		nested := nestedValidatableFields(s, validatableStructs)

		if len(rules) == 0 && len(nested) == 0 {
			continue
		}

		wrote = true
		fmt.Fprintf(&body, "func (in %s) Validate() error {\n", s.Name)
		for _, fr := range rules {
			body.WriteString(generateFieldChecks(fr))
		}
		for _, nf := range nested {
			body.WriteString(generateNestedCheck(nf))
		}
		body.WriteString("\treturn nil\n}\n\n")
	}

	if !wrote {
		return ""
	}

	return body.String()
}

func computeValidatableStructs(structs []StructInfo) map[string]bool {
	result := map[string]bool{}

	for _, s := range structs {
		if len(fieldRules(s)) > 0 {
			result[s.Name] = true
		}
	}

	for {
		changed := false

		for _, s := range structs {
			if result[s.Name] {
				continue
			}

			if len(nestedValidatableFields(s, result)) > 0 {
				result[s.Name] = true
				changed = true
			}
		}

		if !changed {
			break
		}
	}

	return result
}

type nestedField struct {
	FieldName string
	TypeName  string
	Kind      string
}

func nestedValidatableFields(s StructInfo, validatable map[string]bool) []nestedField {
	var result []nestedField

	for _, f := range s.Fields {
		switch {
		case strings.HasPrefix(f.Type, "*"):
			typeName := strings.TrimPrefix(f.Type, "*")
			if validatable[typeName] {
				result = append(result, nestedField{FieldName: f.Name, TypeName: typeName, Kind: "pointer"})
			}
		case strings.HasPrefix(f.Type, "[]"):
			typeName := strings.TrimPrefix(f.Type, "[]")
			if validatable[typeName] {
				result = append(result, nestedField{FieldName: f.Name, TypeName: typeName, Kind: "slice"})
			}
		case strings.HasPrefix(f.Type, "map["):
			closeIdx := strings.Index(f.Type, "]")
			if closeIdx == -1 {
				continue
			}
			valueType := f.Type[closeIdx+1:]
			if validatable[valueType] {
				result = append(result, nestedField{FieldName: f.Name, TypeName: valueType, Kind: "map"})
			}
		default:
			if validatable[f.Type] {
				result = append(result, nestedField{FieldName: f.Name, TypeName: f.Type, Kind: "struct"})
			}
		}
	}

	return result
}

func generateNestedCheck(nf nestedField) string {
	switch nf.Kind {
	case "pointer":
		return fmt.Sprintf(
			"\tif in.%s != nil {\n\t\tif err := in.%s.Validate(); err != nil {\n\t\t\treturn err\n\t\t}\n\t}\n",
			nf.FieldName, nf.FieldName,
		)
	case "slice":
		return fmt.Sprintf(
			"\tfor _, item := range in.%s {\n\t\tif err := item.Validate(); err != nil {\n\t\t\treturn err\n\t\t}\n\t}\n",
			nf.FieldName,
		)
	case "map":
		return fmt.Sprintf(
			"\tfor _, item := range in.%s {\n\t\tif err := item.Validate(); err != nil {\n\t\t\treturn err\n\t\t}\n\t}\n",
			nf.FieldName,
		)
	case "struct":
		return fmt.Sprintf(
			"\tif err := in.%s.Validate(); err != nil {\n\t\treturn err\n\t}\n",
			nf.FieldName,
		)
	default:
		return ""
	}
}

type fieldRule struct {
	FieldName string
	Rules     []string
}

func fieldRules(s StructInfo) []fieldRule {
	var result []fieldRule
	for _, f := range s.Fields {
		rules := extractValidateRules(f.Tag)
		if len(rules) == 0 {
			continue
		}
		result = append(result, fieldRule{FieldName: f.Name, Rules: rules})
	}
	return result
}

func generateFieldChecks(fr fieldRule) string {
	var out strings.Builder

	if len(fr.Rules) > 0 && fr.Rules[0] == "dive" {
		innerRules := fr.Rules[1:]
		fmt.Fprintf(&out, "\tfor idx, v := range in.%s {\n", fr.FieldName)
		for _, rule := range innerRules {
			out.WriteString(generateDiveCheck(fr.FieldName, rule))
		}
		out.WriteString("\t}\n")
		return out.String()
	}

	if len(fr.Rules) > 0 && fr.Rules[0] == "dive_key" {
		innerRules := fr.Rules[1:]
		fmt.Fprintf(&out, "\tfor k := range in.%s {\n", fr.FieldName)
		for _, rule := range innerRules {
			out.WriteString(generateDiveKeyCheck(fr.FieldName, rule))
		}
		out.WriteString("\t}\n")
		return out.String()
	}

	for _, rule := range fr.Rules {
		switch {
		case rule == "required":
			fmt.Fprintf(&out,
				"\tif in.%s == \"\" {\n\t\treturn fmt.Errorf(\"%s is required\")\n\t}\n",
				fr.FieldName, fr.FieldName,
			)
		case rule == "email":
			fmt.Fprintf(&out,
				"\tif !strings.Contains(in.%s, \"@\") {\n\t\treturn fmt.Errorf(\"%s must be a valid email\")\n\t}\n",
				fr.FieldName, fr.FieldName,
			)
		case strings.HasPrefix(rule, "min="):
			n := strings.TrimPrefix(rule, "min=")
			fmt.Fprintf(&out,
				"\tif len(in.%s) < %s {\n\t\treturn fmt.Errorf(\"%s must be at least %s characters\")\n\t}\n",
				fr.FieldName, n, fr.FieldName, n,
			)
		case strings.HasPrefix(rule, "max="):
			n := strings.TrimPrefix(rule, "max=")
			fmt.Fprintf(&out,
				"\tif len(in.%s) > %s {\n\t\treturn fmt.Errorf(\"%s must be at most %s characters\")\n\t}\n",
				fr.FieldName, n, fr.FieldName, n,
			)
		}
	}

	return out.String()
}

func generateDiveCheck(fieldName, rule string) string {
	switch {
	case rule == "required":
		return fmt.Sprintf(
			"\t\tif v == \"\" {\n\t\t\treturn fmt.Errorf(\"%s[%%d] is required\", idx)\n\t\t}\n",
			fieldName,
		)
	case strings.HasPrefix(rule, "min="):
		n := strings.TrimPrefix(rule, "min=")
		return fmt.Sprintf(
			"\t\tif len(v) < %s {\n\t\t\treturn fmt.Errorf(\"%s[%%d] must be at least %s characters\", idx)\n\t\t}\n",
			n, fieldName, n,
		)
	case strings.HasPrefix(rule, "max="):
		n := strings.TrimPrefix(rule, "max=")
		return fmt.Sprintf(
			"\t\tif len(v) > %s {\n\t\t\treturn fmt.Errorf(\"%s[%%d] must be at most %s characters\", idx)\n\t\t}\n",
			n, fieldName, n,
		)
	default:
		return ""
	}
}

func generateDiveKeyCheck(fieldName, rule string) string {
	switch {
	case rule == "required":
		return fmt.Sprintf(
			"\t\tif k == \"\" {\n\t\t\treturn fmt.Errorf(\"%s has an empty key\")\n\t\t}\n",
			fieldName,
		)
	case strings.HasPrefix(rule, "min="):
		n := strings.TrimPrefix(rule, "min=")
		return fmt.Sprintf(
			"\t\tif len(k) < %s {\n\t\t\treturn fmt.Errorf(\"%s key %%q must be at least %s characters\", k)\n\t\t}\n",
			n, fieldName, n,
		)
	case strings.HasPrefix(rule, "max="):
		n := strings.TrimPrefix(rule, "max=")
		return fmt.Sprintf(
			"\t\tif len(k) > %s {\n\t\t\treturn fmt.Errorf(\"%s key %%q must be at most %s characters\", k)\n\t\t}\n",
			n, fieldName, n,
		)
	default:
		return ""
	}
}
